### ISSUE TITLE
Imports: Contemplation and rework

### ISSUE THREAD

**Issue by kittywitch** [kittywitch/nixfiles#17]
The current state of imports is somewhat improved from how it used to be, however, more work could be done on recursiveMod and nodeImport.

- [ ] Further work on recursiveMod
	- [ ] Centralized settings definition
	- [ ] Refactors to be saner code
	- [ ] Require far less hacks
	- [ ] Allow merging of tree structures from multiple results in places
- [ ] Lighter base profile
	- [ ] Contemplate nomenclature (lite? embedded? server? What does the heavier extension to base become?)
- [x] Shared profile
- [x] Migrate shinmyoumaru configuration into [profiles/hardware/raspi][].

[profiles/hardware/raspi]: https://github.com/kittywitch/nixfiles/blob/main/config/profiles/hardware/raspi.nix
