### ISSUE TITLE
nixfiles-base & nixexprs: Rework

### ISSUE THREAD

**Issue by kittywitch** [kittywitch/nixfiles#7]
I started two separate repositories: [kittywitch/nixfiles-base][] and [kittywitch/nixexprs][].

The former provides a template for others to adopt the underlying functionalities provided in this repository. The latter is reusable(?) modules and packages.

- [x] [kittywitch/nixexprs][] inhoused as exprs
- [x] Merged local changes with exprs
- [ ] Module reusability prioritisation
- [ ] Stabilize repository structure
- [ ] Redo [kittywitch/nixfiles-base] with stabilized repository

[kittywitch/nixfiles-base]: https://github.com/kittywitch/nixfiles-base
[kittywitch/nixexprs]: https://github.com/kittywitch/nixexprs
